import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "bootstrap/dist/css/bootstrap.min.css";
// import "./globals.css";

import ProviderQuery from '#/components/ProviderQuery';
import NextAuth, { getServerSession } from "next-auth";
import SessionProvider from "#/components/SessionProvider";

import Header from "#/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <SessionProvider session={session}>
      <ProviderQuery>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            {children}
          </body>
        </html>
      </ProviderQuery>
    </SessionProvider>
  );
}
